//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_ScSvStub.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string TargetAppDirectory {
            get {
                return ((string)(this["TargetAppDirectory"]));
            }
            set {
                this["TargetAppDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SchackMediaViewer")]
        public string TargetAppFilenameBase {
            get {
                return ((string)(this["TargetAppFilenameBase"]));
            }
            set {
                this["TargetAppFilenameBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".exe")]
        public string TargetAppFilenameExtension {
            get {
                return ((string)(this["TargetAppFilenameExtension"]));
            }
            set {
                this["TargetAppFilenameExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" @\"C:\\Users\\LocallyMe\\Source\\Repos\\SchackMediaViewer\\V1\\SchackMediaViewer\\bin\\Deb" +
            "ug\"")]
        public string MainTargetAppDirectory {
            get {
                return ((string)(this["MainTargetAppDirectory"]));
            }
            set {
                this["MainTargetAppDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SchackMediaViewer")]
        public string MainTargetAppFilenameBase {
            get {
                return ((string)(this["MainTargetAppFilenameBase"]));
            }
            set {
                this["MainTargetAppFilenameBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainTargetAppFilenameAppendage {
            get {
                return ((string)(this["MainTargetAppFilenameAppendage"]));
            }
            set {
                this["MainTargetAppFilenameAppendage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".exe")]
        public string MainTargetAppFilenameExtension {
            get {
                return ((string)(this["MainTargetAppFilenameExtension"]));
            }
            set {
                this["MainTargetAppFilenameExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" @\"C:\\Users\\LocallyMe\\Source\\Repos\\SchackMediaViewer\\V1\\SchackMediaViewer\\bin\\Deb" +
            "ug\"")]
        public string CPPreviewTargetAppDirectory {
            get {
                return ((string)(this["CPPreviewTargetAppDirectory"]));
            }
            set {
                this["CPPreviewTargetAppDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SchackMediaViewer")]
        public string CPPreviewTargetAppFilenameBase {
            get {
                return ((string)(this["CPPreviewTargetAppFilenameBase"]));
            }
            set {
                this["CPPreviewTargetAppFilenameBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_CPP_")]
        public string CPPreviewTargetAppFilenameAppendage {
            get {
                return ((string)(this["CPPreviewTargetAppFilenameAppendage"]));
            }
            set {
                this["CPPreviewTargetAppFilenameAppendage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".exe")]
        public string CPPreviewTargetAppFilenameExtension {
            get {
                return ((string)(this["CPPreviewTargetAppFilenameExtension"]));
            }
            set {
                this["CPPreviewTargetAppFilenameExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" @\"C:\\Users\\LocallyMe\\Source\\Repos\\SchackMediaViewer\\V1\\SchackMediaViewer\\bin\\Deb" +
            "ug\"")]
        public string CPConfigureTargetAppDirectory {
            get {
                return ((string)(this["CPConfigureTargetAppDirectory"]));
            }
            set {
                this["CPConfigureTargetAppDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SchackMediaViewer")]
        public string CPConfigureTargetAppFilenameBase {
            get {
                return ((string)(this["CPConfigureTargetAppFilenameBase"]));
            }
            set {
                this["CPConfigureTargetAppFilenameBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_CPC_")]
        public string CPConfigureTargetAppFilenameAppendage {
            get {
                return ((string)(this["CPConfigureTargetAppFilenameAppendage"]));
            }
            set {
                this["CPConfigureTargetAppFilenameAppendage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".exe")]
        public string CPConfigureTargetAppFilenameExtension {
            get {
                return ((string)(this["CPConfigureTargetAppFilenameExtension"]));
            }
            set {
                this["CPConfigureTargetAppFilenameExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDevDirectory {
            get {
                return ((bool)(this["UseDevDirectory"]));
            }
            set {
                this["UseDevDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSeparateExes {
            get {
                return ((bool)(this["UseSeparateExes"]));
            }
            set {
                this["UseSeparateExes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCommandLines {
            get {
                return ((bool)(this["ShowCommandLines"]));
            }
            set {
                this["ShowCommandLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowModifierKeystates {
            get {
                return ((bool)(this["ShowModifierKeystates"]));
            }
            set {
                this["ShowModifierKeystates"] = value;
            }
        }
    }
}
